### ISSUE TITLE
This hack is a total blast!

### ISSUE THREAD

**Issue by Orochikyocr** [GameHackFan/karnovre#1]
I only wanted to say thanks. I am part of a small community in Costa Rica. We love old fighting games and I like Karnov but I have to admit that some inputs are awful for both old and newcomers.
Thanks to this patch, we got some 20-year-old players getting into the game as the inputs are way more friendly without the need of being straight dumb as some modern fighting games.
Also, the new movements and supers added are very cool. The gameplay balance is well done too.
We are having a total blast, playing the hack every weekend on Fightcade 2.

I would like to make some suggestions, 
Hurry music should be played at the match point. I am listening to the OST right now and it is good but it can't be appreciated as the "hurry music" is constantly interrupting the stage music every single round.
Universal overhead for all characters.
Technical for normal grabs. I need to accept that this could break the gameplay as normal grabs sometimes are the only way to punish some movements. Still, it would be cool and give the game a more modern feeling.
More hits for Marstorius weak point. Every single character can put Mars in a dizzy state with two simple combos.

I know this is a lot of work, but I can't help but do this list. The game is already on another level with this patch. I do not think I'll be back to the original one ever. Thanks for the hard work.

**Comment by GameHackFan** [comment]
Hi, that's great, hope you guys have lots of fun. Right now I am almost at the point of releasing the version 0.2, I don't know if that is the one you guys are playing.

The hurry music change could be made, might not be a hard change to do, so maybe the 0.3 version can have it.

About everyone having an overhead, I like the idea of adding more attacking possibilities and ways to make it harder for people to block, but I don't have any new sprites to do that, right now I also don't know how to add sprites. Even after finding a way to handle adding new sprites, I don't know what people will think about this change.

Now, stuff like anti normal throws, for me personally, they are a must in all fighting games because it enhances grappling characters since they will be the only characters that you won't be able to avoid being grabbed. I have no clue if I will add this feature in the future because I don't know if it will be well accepted.

About the dizzy spots, the version 0.2 changes that in a way that it won't matter how easy it is to make characters dizzy, and the changes the version 0.2 brings, for me, actually makes Marstorius weak spot the best one in the game.

**Comment by Orochikyocr** [comment]
We play a game called Under Night in Birth. The game has a universal overhead system. If I press Down + D the player will do a short hop and throw an aerial normal attack, which in most cases uses the same sprite as other normal air attacks. You could do something like that.  In this way, new sprites aren't needed.
The command could be down + CD, the character will short hop like a KOF small jump and use a pre-chosen(by the code) attack.
I can't wait to see the changes. We will celebrate a tournament soon and record it, once it is done I will share the link to the video here.
Thanks again.

**Comment by GameHackFan** [comment]
That is indeed possible, I think Samurai Shodown II Perfect hack was doing that. That could be added basically as a new move to every character, and the input could be FORWARD or BACK + CD, that would make more sense.

About adding it, I don't know, we will see in the future.

**Comment by Orochikyocr** [comment]
I was thinking of running this hack for the Vortex Gallery Online. Would you happen to know where the FHD players are gathering? I would like to see if some of them could join us. If there is a discord, the better.

**Comment by GameHackFan** [comment]
Yes, there is a discord server, I got invited to it a long time ago.

**Comment by Orochikyocr** [comment]
Would you kindly ask them for an invitation link to that server?

**Comment by Orochikyocr** [comment]
https://www.twitch.tv/videos/2189551574
The tournament I talked about, we were 8. We love the patch. Karnov is just kind of OP, still. I hope you like it.

**Comment by GameHackFan** [comment]
Nice tournament, the v0.2 version brings more nerfs to karnov and lee's dive.

This is the discord invitation https://discord.gg/4v2NyhB.
